version: '3.8'

services:
  chat-service:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - chat-network
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  chat-network: