services:
  chat-service:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    container_name: chat_service
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
    depends_on:
      - mongo
    networks:
      - chat-network
    restart: always

  mongo:
    image: mongo:6.0-jammy
    container_name: mongodb
    command: [
      "--storageEngine=wiredTiger",
      "--wiredTigerCacheSizeGB=0.2",
      "--nojournal",
      "--nounixsocket"
    ]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network
    restart: always

volumes:
  mongodb_data:

networks:
  chat-network:
    driver: bridge