services:
  chat-service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chat_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      PORT: ${CHAT_PORT}
    ports:
      - "${CHAT_PORT}:${CHAT_PORT}"
    networks:
      - marketplace_network
    restart: always

networks:
  marketplace_network:
    external: true